clear all;close all
%cas SH
syms S1 S2 h kz z
u=S1*exp(-i*kz*z)+S2*exp(i*kz*(z-h))
int(u*conj(u),0,h)

% res
%     S1*conj(S2)*((kz*exp(-h*kz*i)*i)/(kz^2 + abs(kz)^2) - (kz*exp((h*abs(kz)^2*i)/kz)*i)/(kz^2 + abs(kz)^2)) + ...
%     S2*conj(S1)*((kz*exp(-h*kz*i)*i)/(kz^2 + abs(kz)^2) - (kz*exp((h*abs(kz)^2*i)/kz)*i)/(kz^2 + abs(kz)^2)) + ...
%     (S1*kz*conj(S1)*(exp((h*abs(kz)^2*i)/kz)*exp(-h*kz*i) - 1)*i)/((kz + abs(kz))*(kz - abs(kz))) + ...
%     (S2*kz*conj(S2)*(exp((h*abs(kz)^2*i)/kz)*exp(-h*kz*i) - 1)*i)/((kz + abs(kz))*(kz - abs(kz)))

syms  h kz z real
int(u*conj(u),0,h)
% res
% S1*h*conj(S1) + S2*h*conj(S2) + (S1*sin(h*kz)*conj(S2))/kz + (S2*sin(h*kz)*conj(S1))/kz





%cas PSV
syms S1 S2 S3 S4 kzP kzS
syms  h  z real
u=S1*exp(-1i*kzS*z)+S2*exp(-1i*kzP*z)+S3*exp(1i*kzS*(z-h))+S4*exp(1i*kzP*(z-h));


int(u*conj(u),z,0,h)


E=    S2*conj(S4)*((kzP*exp(-h*kzP*1i)*1i)/(kzP^2 + abs(kzP)^2) - (kzP*exp((h*abs(kzP)^2*1i)/kzP)*1i)/(kzP^2 + abs(kzP)^2)) ...
    + S4*conj(S2)*((kzP*exp(-h*kzP*1i)*1i)/(kzP^2 + abs(kzP)^2) - (kzP*exp((h*abs(kzP)^2*1i)/kzP)*1i)/(kzP^2 + abs(kzP)^2)) ...
    + S1*conj(S3)*((kzS*exp(-h*kzS*1i)*1i)/(kzS^2 + abs(kzS)^2) - (kzS*exp((h*abs(kzS)^2*1i)/kzS)*1i)/(kzS^2 + abs(kzS)^2)) ...
    + S3*conj(S1)*((kzS*exp(-h*kzS*1i)*1i)/(kzS^2 + abs(kzS)^2) - (kzS*exp((h*abs(kzS)^2*1i)/kzS)*1i)/(kzS^2 + abs(kzS)^2)) ...
    - (S2*exp(-h*kzP*1i)*conj(S1)*(exp(h*kzP*1i)*1i - exp(h*conj(kzS)*1i)*1i))/(kzP - conj(kzS)) ...
    - (S4*exp(-h*kzP*1i)*conj(S3)*(exp(h*kzP*1i)*1i - exp(h*conj(kzS)*1i)*1i))/(kzP - conj(kzS)) ...
    - (S1*exp(-h*kzS*1i)*conj(S2)*(exp(h*kzS*1i)*1i - exp(h*conj(kzP)*1i)*1i))/(kzS - conj(kzP)) ...
    - (S3*exp(-h*kzS*1i)*conj(S4)*(exp(h*kzS*1i)*1i - exp(h*conj(kzP)*1i)*1i))/(kzS - conj(kzP)) ...
    - (S2*exp(-h*kzP*1i)*conj(S3)*(exp(h*kzP*1i)*exp(h*conj(kzS)*1i)*1i - 1i))/(kzP + conj(kzS)) ...
    - (S4*exp(-h*kzP*1i)*conj(S1)*(exp(h*kzP*1i)*exp(h*conj(kzS)*1i)*1i - 1i))/(kzP + conj(kzS)) ...
    - (S1*exp(-h*kzS*1i)*conj(S4)*(exp(h*kzS*1i)*exp(h*conj(kzP)*1i)*1i - 1i))/(kzS + conj(kzP)) ...
    - (S3*exp(-h*kzS*1i)*conj(S2)*(exp(h*kzS*1i)*exp(h*conj(kzP)*1i)*1i - 1i))/(kzS + conj(kzP)) ...
    + (S2*kzP*conj(S2)*(exp((h*abs(kzP)^2*1i)/kzP)*exp(-h*kzP*1i) - 1)*1i)/((kzP + abs(kzP))*(kzP - abs(kzP))) ...
    + (S4*kzP*conj(S4)*(exp((h*abs(kzP)^2*1i)/kzP)*exp(-h*kzP*1i) - 1)*1i)/((kzP + abs(kzP))*(kzP - abs(kzP))) ...
    + (S1*kzS*conj(S1)*(exp((h*abs(kzS)^2*1i)/kzS)*exp(-h*kzS*1i) - 1)*1i)/((kzS + abs(kzS))*(kzS - abs(kzS))) ...
    + (S3*kzS*conj(S3)*(exp((h*abs(kzS)^2*1i)/kzS)*exp(-h*kzS*1i) - 1)*1i)/((kzS + abs(kzS))*(kzS - abs(kzS)));


syms S1 S2 S3 S4
syms  h  z real
syms  kzP kzS real
u=S1*exp(kzS*z)+S2*exp(kzP*z)+S3*exp(-kzS*(z-h))+S4*exp(kzP*(z-h));
int(u*conj(u),z,0,h)

E=E+ (S2*conj(S2)*(exp(2*h*kzP) - 1))/(2*kzP) ...
- S4*conj(S1)*(exp(-h*kzP)/(kzP + kzS) - exp(h*kzS)/(kzP + kzS)) ...
- S1*conj(S4)*(exp(-h*kzP)/(kzP + kzS) - exp(h*kzS)/(kzP + kzS)) ...
- (S4*conj(S4)*(exp(-2*h*kzP) - 1))/(2*kzP) ...
+ (S1*conj(S1)*(exp(2*h*kzS) - 1))/(2*kzS) ...
+ (S3*conj(S3)*(exp(2*h*kzS) - 1))/(2*kzS) ...
+ (S2*conj(S3)*(exp(h*kzP) - exp(h*kzS)))/(kzP - kzS) ...
+ (S3*conj(S2)*(exp(h*kzP) - exp(h*kzS)))/(kzP - kzS) ...
+ S1*h*exp(h*kzS)*conj(S3) ...
+ S3*h*exp(h*kzS)*conj(S1) ...
+ (S2*conj(S4)*(exp(h*kzP)/2 - exp(-h*kzP)/2))/kzP ...
+ (S4*conj(S2)*(exp(h*kzP)/2 - exp(-h*kzP)/2))/kzP ...
+ (S1*conj(S2)*(exp(h*kzP + h*kzS) - 1))/(kzP + kzS)  ...
+ (S2*conj(S1)*(exp(h*kzP + h*kzS) - 1))/(kzP + kzS) ...
- (S3*conj(S4)*(exp(h*kzS - h*kzP) - 1))/(kzP - kzS) ...
- (S4*conj(S3)*(exp(h*kzS - h*kzP) - 1))/(kzP - kzS);
  
E= E + 1i*(...
        + (S2*conj(S4) + S4*conj(S2))/(kzP + conj(kzP))*(exp(-h*kzP*1i) - exp(h*conj(kzP)*1i)) ...
        + (S1*conj(S3) + S3*conj(S1))/(kzS + conj(kzS))*(exp(-h*kzS*1i) - exp(h*conj(kzS)*1i)) ...
        + (S2*conj(S2) + S4*conj(S4))/(kzP - conj(kzP))*(exp(1i*h*(conj(kzP)-kzP)) - 1) ...
        + (S1*conj(S1) + S3*conj(S3))/(kzS - conj(kzS))*(exp(1i*h*(conj(kzS)-kzS)) - 1) ...
        - (S2*conj(S1) + S4*conj(S3))/(kzP - conj(kzS))*(1 - exp(1i*h*(conj(kzS)-kzP))) ...
        - (S1*conj(S2) + S3*conj(S4))/(kzS - conj(kzP))*(1 - exp(1i*h*(conj(kzP)-kzS))) ...
        - (S2*conj(S3) + S4*conj(S1))/(kzP + conj(kzS))*(exp(1i*h*conj(kzS)) - exp(-1i*h*kzP)) ...
        - (S1*conj(S4) + S3*conj(S2))/(kzS + conj(kzP))*(exp(1i*h*conj(kzP)) - exp(-1i*h*kzS)));
    
        %         E= E + 1i*(...
    %             + (S2*conj(S4) + S4*conj(S2))*kzP/(kzP^2 + abs(kzP)^2)*(exp(-h*kzP*1i) - exp(h*abs(kzP)^2*1i/kzP)) ...
    %             + (S1*conj(S3) + S3*conj(S1))*kzS/(kzS^2 + abs(kzS)^2)*(exp(-h*kzS*1i) - exp(h*abs(kzS)^2*1i/kzS)) ...
    %             + (S2*conj(S2) + S4*conj(S4))*kzP/(kzP^2 - abs(kzP)^2)*(exp(1i*h*(abs(kzP)^2/kzP-kzP)) - 1) ...
    %             + (S1*conj(S1) + S3*conj(S3))*kzS/(kzS^2 - abs(kzS)^2)*(exp(1i*h*(abs(kzS)^2/kzS-kzS)) - 1) ...
    %             - (S2*conj(S1) + S4*conj(S3))    /(kzP - conj(kzS))   *(1 - exp(1i*h*(conj(kzS)-kzP))) ...
    %             - (S1*conj(S2) + S3*conj(S4))    /(kzS - conj(kzP))   *(1 - exp(1i*h*(conj(kzP)-kzS))) ...
    %             - (S2*conj(S3) + S4*conj(S1))    /(kzP + conj(kzS))   *(exp(1i*h*conj(kzS)) - exp(-1i*h*kzP)) ...
    %             - (S1*conj(S4) + S3*conj(S2))    /(kzS + conj(kzP))   *(exp(1i*h*conj(kzP)) - exp(-1i*h*kzS)));


syms S1 S2 S3 S4
syms  h  z real
syms  kzP kzS real
u=S1*exp(-1i*kzS*z)+S2*exp(kzP*z)+S3*exp(1i*kzS*(z-h))+S4*exp(kzP*(z-h));
int(u*conj(u),z,0,h)


clear all;
syms S1 S2 S3 S4 
syms z h kzP kzS real
assume(kzS>0) 
assume(kzP>0) 

u=S1*exp(-kzS*z)+S2*exp(-kzP*z);
int(u*conj(u),z,0,inf)

% res
(S2*conj(S2))/(2*kzP) + (S1*conj(S1))/(2*kzS) + (S1*conj(S2))/(kzP + kzS) + (S2*conj(S1))/(kzP + kzS)