function E=NormE_PSV(kzS,kzP,S1,S2,S3,S4,h)

if real(kzS)~=0 && real(kzP)~=0
    E= 1i*(...
        + (S2*conj(S4) + S4*conj(S2))/(kzP + conj(kzP))*(exp(-h*kzP*1i) - exp(h*conj(kzP)*1i)) ...
        + (S1*conj(S3) + S3*conj(S1))/(kzS + conj(kzS))*(exp(-h*kzS*1i) - exp(h*conj(kzS)*1i)) ...
        + (S2*conj(S2) + S4*conj(S4))/(kzP - conj(kzP))*(exp(1i*h*(conj(kzP)-kzP)) - 1) ...
        + (S1*conj(S1) + S3*conj(S3))/(kzS - conj(kzS))*(exp(1i*h*(conj(kzS)-kzS)) - 1) ...
        - (S2*conj(S1) + S4*conj(S3))/(kzP - conj(kzS))*(1 - exp(1i*h*(conj(kzS)-kzP))) ...
        - (S1*conj(S2) + S3*conj(S4))/(kzS - conj(kzP))*(1 - exp(1i*h*(conj(kzP)-kzS))) ...
        - (S2*conj(S3) + S4*conj(S1))/(kzP + conj(kzS))*(exp(1i*h*conj(kzS)) - exp(-1i*h*kzP)) ...
        - (S1*conj(S4) + S3*conj(S2))/(kzS + conj(kzP))*(exp(1i*h*conj(kzP)) - exp(-1i*h*kzS)));
elseif real(kzS)==0 && real(kzP)==0
    kzS = imag(kzS);
    kzP = imag(kzP);
    
    if max(abs(S4),abs(S3))<1e-10*min(abs(S2),abs(S1))
        E= (S2*conj(S2)*(exp( 2*h*kzP) - 1))/(2*kzP) ...
            + (S1*conj(S1))*(exp(2*h*kzS) - 1)/(2*kzS) ...
            + (S1*conj(S2)+S2*conj(S1))*(exp(h*kzP + h*kzS) - 1)/(kzP + kzS);
    else
        E=    (S2*conj(S2)*(exp( 2*h*kzP) - 1))/(2*kzP) ...
            - (S4*conj(S4)*(exp(-2*h*kzP) - 1))/(2*kzP) ...
            + (S2*conj(S4)+S4*conj(S2))*(exp( h*kzP) - exp(-h*kzP))/(2*kzP) ...
            - (S4*conj(S1)+S1*conj(S4))*(exp(-h*kzP) - exp(h*kzS))/(kzP + kzS) ...
            + (S2*conj(S3)+S3*conj(S2))*(exp( h*kzP) - exp(h*kzS))/(kzP - kzS) ...
            + (S1*conj(S1)+S3*conj(S3))*(exp(2*h*kzS) - 1)/(2*kzS) ...
            + (S1*conj(S3)+S3*conj(S1))*h*exp(h*kzS) ...
            + (S1*conj(S2)+S2*conj(S1))*(exp(h*kzP + h*kzS) - 1)/(kzP + kzS)  ...
            - (S3*conj(S4)+S4*conj(S3))*(exp(h*kzS - h*kzP) - 1)/(kzP - kzS);
    end
elseif real(kzS)~=0 && real(kzP)==0
    kzP = imag(kzP);
    
    E= (S2*conj(S4)+S4*conj(S2))*sinh(h*kzP)/kzP ...
        + (S3*conj(S1)+S1*conj(S3))* sin(h*kzS)/kzS ...
        + (S1*conj(S1) + S3*conj(S3))*h ...
        + (S2*conj(S2)*(exp( 2*h*kzP) - 1))/(2*kzP) ...
        - (S4*conj(S4)*(exp(-2*h*kzP) - 1))/(2*kzP) ...
        + (S2*conj(S3)*(exp( h*kzP) - exp( h*kzS*1i)))/(kzP - kzS*1i) ...
        - (S1*conj(S4)*(exp(-h*kzP) - exp(-h*kzS*1i)))/(kzP - kzS*1i) ...
        - (S4*conj(S3)*(exp(h*(-kzP + kzS*1i))   - 1))/(kzP - kzS*1i) ...
        + (S1*conj(S2)*(exp(h*( kzP - kzS*1i))   - 1))/(kzP - kzS*1i) ...
        +  S2*conj(S1)*(exp(h*( kzP + kzS*1i))   - 1) /(kzP + kzS*1i) ...
        -  S3*conj(S4)*(exp(h*(-kzP - kzS*1i))   - 1) /(kzP + kzS*1i) ...
        +  S3*conj(S2)*(exp( h*kzP) - exp(-h*kzS*1i) )/(kzP + kzS*1i) ...
        -  S4*conj(S1)*(exp(-h*kzP) - exp( h*kzS*1i) )/(kzP + kzS*1i);
else
    wtf
end