!Control file for program dst4list
!Name of output file:
  dst4list.out
!Sign of west longitude:
 -1.0
!Coordinates of reference station:
 16.254  -98.531    Epicenter
!List of coordinates for which distance from reference station
!will be computed (stacode a string up to 30 characters long):
  PNIG 16.394 -98.127
  JAMI 16.284 -97.821
  SJLL 16.658 -98.498
  MT02 16.54 -98.25
  LG01 16.31 -98.44
  LA03 16.67 -98.05
  HZ04 16.30 -97.91
 stop

